nelmio_api_doc:
    documentation:
        info:
            title: Travel
            description: Train project
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/travel/api1(?!/doc$) # Accepts routes under /api except /api/doc
